### ISSUE TITLE
Unable to login and 404 on the demo api

### ISSUE THREAD

**Issue by vlom31** [Cambalab/vue-admin#176]
**Describe the bug**
After installing the app; I'm unable to login.

First is I don't know what username & password I'm supposed to enter in the demo login page.

Second, I get a 404 not found for localhost:8888/api/auth/ (or any other url on that port for that matter) even though the server is running (I followed the steps in the README with no errors).

**Screenshots**
https://www.evernote.com/l/AFpy2wf08uZN4IgFHEMmp-AoY3ppd0MEigY

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15
 - Chrome 78

**Comment by sgobotta** [comment]
Thanks for opening this issue.

You're right, we haven't documented properly how to log in to the demo site. We don't really need to since we're planning to move the demo and the test server to another repository. But I agree with you, we should put that information somewhere meanwhile.

Until we update the `README.md` you can find two hardcoded users in the [`auth`](https://github.com/Cambalab/vue-admin/blob/master/utils/server-test/services/auth.js#L18) service or use:

**username:** dev@camba.coop
**password:** 123456

I'll take a look at the error. As far as I can see, we did not implement a list of the `api` routes of the test server when you visit `.../api`, that's what I see in the screenshot.

**Comment by sgobotta** [comment]
> **Describe the bug**
> After installing the app; I'm unable to login.
> 
> First is I don't know what username & password I'm supposed to enter in the demo login page.

You'll be able to login using credentials mentioned above

> Second, I get a 404 not found for localhost:8888/api/auth/ (or any other url on that port for that matter) even though the server is running (I followed the steps in the README with no errors).

When I visit `localhost:8888/api/auth/` the message looks like this:

![image](https://user-images.githubusercontent.com/17838461/66708907-f834d000-ed2e-11e9-92a9-9d62fba73a09.png)

Which makes sense, since the endpoint requires a username and a password that exists in the server users "fixture", meaning that endpoint works.

This disussion makes me think we just need an updated `README.md` providing credentials for the demo app. Apart from that, are proposing an enhancement in the `utils/server` scripts?
